server:
  port: 9996
eureka:
  client:
    service-url:
      defaultZone : http://localhost:9000/eureka/,http://localhost:9001/eureka/
spring:
  application:
    name: 001-springcloud-feign

feign:
  hystrix:
    enabled: true
