server:
  port: 9000 #端口
spring:
  application:
    name: 01-springcloud-product #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sjj?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456