spring:
  cloud:
    consul:
        host: 127.0.0.1 #ConsulServer请求地址
        port: 8500 #ConsulServer端口
        discovery: #是否注册
          register: true #实例ID
          instance-id: ${spring.application.name}-1 #服务实例名称
          service-name: ${spring.application.name} #服务实例端口
          port: ${server.port} #健康检查路径
          healthCheckPath: /actuator/health #健康检查时间间隔
          healthCheckInterval: 15s #开启ip地址注册
          prefer-ip-address: true #实例的请求ip
          ip-address: ${spring.cloud.client.ip-address}

