server:
  port: 9998
spring:
  application:
    name: 001-springcloud-consumer
eureka:
  instance:
    prefer-ip-address: true
    instance-id: http://${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/