server:
  port: 9999
spring:
  application:
    name: 001-springcloud-provider
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: http://${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/
